name: Trigger auto deployment for container-hackathon-kemenkeu-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-hackathon-kemenkeu-api-AutoDeployTrigger-67912126-5f06-4c34-8811-4df44f97935b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERHACKATHONKEMENKEUAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERHACKATHONKEMENKEUAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERHACKATHONKEMENKEUAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: nawainternal.azurecr.io
          registryUsername: ${{ secrets.CONTAINERHACKATHONKEMENKEUAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERHACKATHONKEMENKEUAPI_REGISTRY_PASSWORD }}
          containerAppName: container-hackathon-kemenkeu-api
          resourceGroup: NAWA-RESEARCH-DEVELOPMENT
          imageToBuild: nawainternal.azurecr.io/container-hackathon-kemenkeu-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


